name: Create Meeting Artifacts (Scheduled)

on:
  schedule:
    - cron: '0 10 * * 1'

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meeting_group:
          - benchmarking
          - build
          - cross_project_council
          - diag
          - diag_deepdive
          - ecosystem_report
          - loaders
          - modules
          - next-10
          - outreach
          - package-maintenance
          - package_metadata_interop
          - Release
          - security-wg
          - security_collab
          - standards
          - sustainability_collab
          - tsc
          - tooling
          - typescript
          - uvwasi
          - userfeedback
          - web-server-frameworks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Read USER field from meeting_base file
        id: read-vars
        run: |
          meeting_group="${{ matrix.meeting_group }}"
          user=$(grep '^USER=' "templates/meeting_base_${meeting_group}" | cut -d'=' -f2 | xargs)
          hackmd_team_name=$(grep '^HACKMD_TEAM_NAME=' "templates/meeting_base_${meeting_group}" | cut -d'=' -f2 | xargs)
          echo "user=$user" >> $GITHUB_OUTPUT
          echo "hackmd_team_name=$hackmd_team_name" >> $GITHUB_OUTPUT

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          owner: ${{ steps.read-vars.outputs.user }}

      - name: Create meeting artifacts
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          HACKMD_API_TOKEN: ${{ secrets.HACKMD_API_TOKEN }}
          HACKMD_TEAM_NAME: ${{ steps.read-vars.outputs.hackmd_team_name }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node create-node-meeting-artifacts.mjs ${{ matrix.meeting_group }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: meeting-artifacts-${{ matrix.meeting_group }}
          path: |
            ~/.make-node-meeting/
            *.md
          retention-days: 7
          if-no-files-found: ignore
