name: Create Meeting Artifacts

on:
  # Run every Monday at 10 AM UTC (adjust as needed)
  schedule:
    - cron: '0 10 * * 1'

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      meeting_group:
        description: 'Meeting group to create artifacts for'
        required: true
        type: choice
        options:
          - uvwasi
          - tsc
          - build
          - diag
          - diag_deepdive
          - typescript
          - Release
          - cross_project_council
          - modules
          - tooling
          - security-wg
          - next-10
          - package-maintenance
          - package_metadata_interop
          - ecosystem_report
          - sustainability_collab
          - standards
          - security_collab
          - loaders
          - web-server-frameworks

jobs:
  create-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create meeting artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HACKMD_API_TOKEN: ${{ secrets.HACKMD_API_TOKEN }}
          HACKMD_TEAM_NAME: ${{ secrets.HACKMD_TEAM_NAME }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node create-node-meeting-artifacts.mjs ${{ github.event.inputs.meeting_group }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: meeting-artifacts-${{ github.event.inputs.meeting_group || 'tsc' }}
          path: |
            ~/.make-node-meeting/
            *.md
          retention-days: 7
          if-no-files-found: ignore
